<template>
  <div
    class="h-full fixed left-0 top-14 sm:top-0 z-20 shadow-xs transition-all duration-200 ease-in flex flex-col"
    :class="{
      [bgColor]: true,
      'hidden sm:w-16 sm:block': is_collapsed,
      'w-full sm:w-64': !is_collapsed,
      'right-0': is_mobile,
    }"
  >
    <div
      v-if="!is_mobile"
      class="h-12 text-center flex flex-col justify-center font-medium text-xl pt-3"
    >
      <div
        :class="{ hidden: is_collapsed }"
        class="px-3 py-4"
      >
        <template v-if="show_text">
          <slot
            name="logo"
            :is_collapsed="is_collapsed"
          />
        </template>
      </div>
    </div>
    <div class="flex flex-col flex-grow mt-8">
      <div class="flex flex-col pt-0 sm:pt-6 flex-grow-0">
        <div
          v-for="item in items"
          :key="item.meta.label"
          class="nav-link"
          :class="{
            selected: linkIsCurrentLink(item),
          }"
          @click="navigateTo(item)"
        >
          <slot
            name="nav-item"
            :selected="linkIsCurrentLink(item)"
            :item="item"
            :is_collapsed="is_collapsed"
          >
            {{ item.meta.label }}
          </slot>
        </div>
      </div>
    </div>
    <div
      v-if="!is_collapsed && version"
      class="text-center py-2 mt-auto text-blue"
    >
      <span>versione</span>
      <span>{{ version }}</span>
    </div>
  </div>
</template>

<script>
import SideNavMixin from '@/mixins/sidenav.mixin.js'
import { mapState } from 'vuex'

export default {
  name: 'SideNav',
  mixins: [SideNavMixin],
  props: {
    bgColor: { required: false, default: 'bg-white', type: String }
  },
  data: () => ({
    value: 0,
    item: 0,
    mini_variant: false,
    selected_action: {}
  }),
  computed: {
    ...mapState('user', {
      user: (state) => state.user
    }),
    currentPath () {
      return this.$router.name
    },
    items () {
      if (!this.$routes.length) {
        return []
      }

      return this.$routes
        .filter((route) => {
          // Only routes with the meta.label have to be present
          // in the SideNav
          return route.meta && route.meta.label !== undefined
        })
        .filter((route) => {
          if (route.meta.roles) {
            if (!this.user) {
              return -1
            }

            let userRole = this.user.role.code.toLowerCase()

            if (this.user.role.code === 'superadmin' && this.user.account) {
              userRole = 'user'
            }

            return route.meta.roles.includes(userRole)
          }

          return true
        })
    },
    version () {
      return this.APPLICATION_VERSION
    }
  },
  beforeMount () {
    this.listenForSideNavCollapseEvent()
  },
  mounted () {},
  methods: {
    doUserAction (action) {
      this.$router.push(action.path)
    },
    navigateTo (link) {
      // Don't navigate to same route or root route
      if (
        link.path != this.$route.name &&
        link.path != this.$route.redirectedFrom
      ) {
        if (this.is_mobile) {
          this.collapseSideBar()
        }
        this.$router.push(link.path)
      }
    },
    linkIsCurrentLink (link) {
      return this.$route.matched.map((l) => l.name).indexOf(link.name) != -1
    }
  }
}
</script>

<style>
/* ----------------------------------------------
* Generated by Animista on 2020-3-16 10:24:13
* Licensed under FreeBSD License.
* See http://animista.net/license for more info.
* w: http://animista.net, t: @cssanimista
* ---------------------------------------------- */

/**
* ----------------------------------------
* animation rotate-90-cw
* ----------------------------------------
*/

.rotate-initial-cw {
  transition: all 0.35s 0.1s;
  transform: rotate(180deg);
}

.rotate-0-cw {
  transform: rotate(180deg);
}

.rotate-180-cw {
  transform: rotate(0deg);
}
</style>
