<template>
  <div
    class="fixed left-0 z-20 flex flex-col h-full top-14 sm:top-0 transition-all duration-200 ease-in"
    :class="{
      [bgColor]: true,
      [shadow]: true,
      [width]: true,
      'hidden sm:block': is_collapsed,
      'w-full sm:w-64': !is_collapsed && !width,
      'right-0': is_mobile,
    }"
  >
    <template>
      <slot name="logo" :is_collapsed="!show_text">
        <div
          v-if="!is_mobile"
          class="flex flex-col justify-center h-12 pt-3 text-xl font-medium text-center"
        />
      </slot>
    </template>
    <div class="h-full overflow-y-auto w-full flex flex-col">
      <div class="flex flex-col w-full mt-8">
        <div class="flex flex-col flex-grow-0 pt-0 sm:pt-6">
          <router-link
            v-for="item in items"
            :key="item.meta.label"
            class="nav-link"
            :class="{
              selected: linkIsCurrentLink(item),
            }"
            :to="item.path"
          >
            <slot
              name="nav-item"
              :selected="linkIsCurrentLink(item)"
              :item="item"
              :is_collapsed="!show_text"
            >
              {{ item.meta.label }}
            </slot>
          </router-link>
        </div>
      </div>
      <template>
        <slot name="general"></slot>
      </template>
      <div
        v-if="!is_collapsed && version"
        class="py-2 mt-auto text-center text-blue-600"
      >
        <span>{{ version }}</span>
      </div>
    </div>
  </div>
</template>

<script>
import { mapState } from "vuex";

export default {
  name: "SideNav",
  props: {
    bgColor: { required: false, default: "bg-white", type: String },
    shadow: { required: false, default: "shadow-xs", type: String },
    width: { required: false, default: "", type: String },
  },
  data: () => ({
    value: 0,
    item: 0,
    mini_variant: false,
    selected_action: {},
  }),
  computed: {
    ...mapState("user", {
      user: (state) => state.user,
    }),
    currentPath() {
      return this.$router.name;
    },
    items() {
      if (!this.$routes.length) {
        return [];
      }

      return this.$routes
        .filter((route) => {
          // Only routes with the meta.label have to be present
          // in the SideNav
          return route.meta && route.meta.label !== undefined;
        })
        .filter((route) => {
          if (route.meta.roles) {
            if (!this.user) {
              return false;
            }

            let userRole = this.getUserRole();

            return route.meta.roles.includes(userRole);
          }

          return true;
        });
    },
    version() {
      return this.APPLICATION_VERSION;
    },
    routesNames() {
      return this.$route.matched
        .filter((l) => {
          return l.meta && l.meta.sectionName;
        })
        .map((l) => l.meta.sectionName);
    },
  },
  beforeMount() {
    this.listenForSideNavCollapseEvent();
  },
  mounted() {},
  methods: {
    doUserAction(action) {
      this.$router.push(action.path);
    },
    navigateTo(link) {
      // Don't navigate to same route or root route
      if (
        link.path != this.$route.name &&
        link.path != this.$route.redirectedFrom
      ) {
        if (this.is_mobile) {
          this.collapseSideBar();
        }
        if (link.name) {
          this.$router.push({
            name: link.name,
          });
        } else {
          this.$router.push(link.path);
        }
      }
    },
    linkIsCurrentLink(link) {
      if (link.name) {
        return this.$route.matched.map((l) => l.name).indexOf(link.name) != -1;
      }
      if (link.meta && link.meta.sectionName) {
        return this.routesNames.includes(link.meta.sectionName);
      }
    },
  },
};
</script>

<style>
/* ----------------------------------------------
* Generated by Animista on 2020-3-16 10:24:13
* Licensed under FreeBSD License.
* See http://animista.net/license for more info.
* w: http://animista.net, t: @cssanimista
* ---------------------------------------------- */

/**
* ----------------------------------------
* animation rotate-90-cw
* ----------------------------------------
*/

.rotate-initial-cw {
  transition: all 0.35s 0.1s;
  transform: rotate(180deg);
}

.rotate-0-cw {
  transform: rotate(180deg);
}

.rotate-180-cw {
  transform: rotate(0deg);
}
</style>
