<template>
  <div
    class="bg-blue-dark h-full fixed left-0 top-14 sm:top-0 z-20 shadow-xs transition-all duration-200 ease-in flex flex-col"
    :class="{
      'hidden sm:w-16 sm:block': is_collapsed,
      'w-full sm:w-64': !is_collapsed,
      'right-0': is_mobile
    }"
  >
    <div
      v-if="!is_mobile"
      class="h-12 text-center flex flex-col justify-center font-medium text-xl pt-3"
    >
      <div :class="{ hidden: is_collapsed }" class="px-3 py-4">
        <template v-if="show_text">
          <div
            class="h-12 bg-contain bg-center bg-no-repeat"
            :style="{
              'background-image': 'url(\'/img/security_logo_white@2x.png\')'
            }"
          ></div>
        </template>
      </div>
      <div
        class="mx-auto flex flex-row items-center h-12 w-12 justify-center"
        :class="{
          hidden: !is_collapsed
        }"
      >
        <p class="m-0 text-indigo-600 leading-relaxed"></p>
      </div>
    </div>

    <div class="flex flex-col flex-grow mt-8">
      <div class="flex flex-col pt-0 sm:pt-6 flex-grow-0">
        <div
          @click="navigateTo(item)"
          :key="item.meta.label"
          class="nav-link"
          :class="{
            selected: linkIsCurrentLink(item)
          }"
          v-for="item in items"
        >
          <div
            :class="{
              selected: linkIsCurrentLink(item),
              'justify-center': is_collapsed
            }"
            :title="is_collapsed ? item.meta.label : ''"
            class="py-3 h-12 px-12 sm:px-0 flex flex-row items-center cursor-pointer no-select"
          >
            <i
              :class="{
                'pr-3': is_collapsed,
                'pr-5': !is_collapsed,
                [item.meta.icon]: true
              }"
              class="text-lg pl-3 text-gray-light ti"
            ></i>
            <span v-if="show_text" class="text-lg text-gray-light">
              {{
              item.meta.label
              }}
            </span>
          </div>
        </div>
      </div>
    </div>

    <div v-if="!is_collapsed" class="text-center py-2 mt-auto text-blue">
      <span>versione</span>
      <span>{{ version }}</span>
    </div>
  </div>
</template>

<script>
import { routes } from "@/utils/routes";
import SideNavMixin from "@/mixin/SideNav.mixin.js";
import { mapState } from "vuex";

export default {
  name: "side-nav",
  mixins: [SideNavMixin],
  mounted() {},
  data: () => ({
    value: 0,
    item: 0,
    mini_variant: false,
    selected_action: {}
    // items: []
  }),
  beforeMount() {
    this.listenForSideNavCollapseEvent();
  },
  methods: {
    doUserAction(action) {
      this.$router.push(action.path);
    },
    navigateTo(link) {
      // Don't navigate to same route or root route
      if (
        link.path != this.$route.name &&
        link.path != this.$route.redirectedFrom
      ) {
        if (this.is_mobile) {
          this.collapseSideBar();
        }
        this.$router.push(link.path);
      }
    },
    linkIsCurrentLink(link) {
      return this.$route.matched.map(l => l.name).indexOf(link.name) != -1;
    }
  },
  computed: {
    ...mapState("user", {
      user: state => state.user
    }),
    currentPath() {
      return this.$router.name;
    },
    items() {
      return routes
        .find(route => route.name == "root")
        .children.filter(route => {
          // Only routes with the meta.label have to be present
          // in the SideNav
          return route.meta && route.meta.label != undefined;
        })
        .filter(route => {
          if (route.meta.roles) {
            if (!this.user) {
              return -1;
            }

            let userRole = this.user.role.code.toLowerCase();

            if (this.user.role.code == "superadmin" && this.user.account) {
              userRole = "user";
            }

            return route.meta.roles.indexOf(userRole) != -1;
          }

          return true;
        });
    },
    version() {
      return this.APPLICATION_VERSION;
    }
  }
};
</script>

<style>
/* ----------------------------------------------
* Generated by Animista on 2020-3-16 10:24:13
* Licensed under FreeBSD License.
* See http://animista.net/license for more info. 
* w: http://animista.net, t: @cssanimista
* ---------------------------------------------- */

/**
* ----------------------------------------
* animation rotate-90-cw
* ----------------------------------------
*/

.rotate-initial-cw {
  transition: all 0.35s 0.1s;
  transform: rotate(180deg);
}

.rotate-0-cw {
  transform: rotate(180deg);
}

.rotate-180-cw {
  transform: rotate(0deg);
}
</style>
